<?php
/**
 * @file
 * Un module qui fournit un bloc afin d'afficher les liens de partage vers les 
 * réseaux sociaux.
 */

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path
 *   Which path of the site we're using to display help
 * @param arg
 *   Array that holds the current path as returned from arg() function
 */
function cybershare_help($path, $arg) {
  switch ($path) {
    case "admin/help#cybershare":
      return '<p>' . t("Affiche des liens de partage vers les réseaux sociaux.") . '</p>';
      break;
  }
}

/**
 * Implements hook_block_info().
 */
function cybershare_block_info() {
  $blocks['cybershare'] = array(
    'info' => t('Réseaux sociaux'),
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function cybershare_block_view($delta = '') {
  switch($delta) {
    case 'cybershare':
      $block['subject'] = t('Partagez');
      if (user_access('access content') ) {
        // Get the actual URL and TITLE
        $url = urlencode($GLOBALS['base_url'] . '/' . request_path());
        $title = urlencode(drupal_get_title());
        // Select which buttons to display and generate their link
        $buttons = array(
          'facebook' => 'http://www.facebook.com/sharer.php?u=' . $url . '&t=' . $title,
          'twitter' => 'http://twitter.com/home?status=' . $title,
          'google' => 'http://plus.google.com/share?url=' . $url,
          'linkedin' => 'http://www.linkedin.com/shareArticle?mini=true&url=' . $url . '&title=' . $title,
        );
        // Create an array of the Social buttons with their icon and link
        foreach ($buttons as $key => $btn) {
          $items[] = '<a href="' . $btn . '" class="cybershare" target="_blank">'. $key . '</a>';
        }
        // Display content
        $block['content'] = '<div class="cybershare">' . implode(' ', $items) . '</div>';
      }
    return $block;
  }
}







