<?php
/**
 * @file
 * Un module qui fournit un bloc afin d'afficher les liens de partage vers les 
 * réseaux sociaux.
 */

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path
 *   Which path of the site we're using to display help
 * @param arg
 *   Array that holds the current path as returned from arg() function
 */
function cybershare_help($path, $arg) {
  switch ($path) {
    case "admin/help#cybershare":
      return '<p>' . t("Affiche des liens de partage vers les réseaux sociaux.") . '</p>';
      break;
  }
} 
